application: love-never-fails
version: 1
runtime: python27
api_version: 1
threadsafe: yes

handlers:
- url: /favicon\.ico
  mime_type: image/png
  static_files: static/favicon.ico
  upload: static/favicon.ico

- url: /fonts
  static_dir: fonts

- url: /css/(.*\.css)
  mime_type: text/css
  static_files: static/css/\1
  upload: static/css/(.*\.css)

- url: /js/(.*\.js)
  mime_type: text/javascript
  static_files: static/js/\1
  upload: static/js/(.*\.js)

- url: /img/(.*\.png)
  mime_type: image/png
  static_files: static/img/\1
  upload: static/img/(.*\.png)

- url: /etlana_bday2015/?
  static_files: static/
  upload: static/
  login: admin
  secure: always

- url: /admin/tasks/odb
  script: odb.app
  secure: always
  login: admin

- url: /admin/odb/.*
  script: odb.app
  secure: always
  login: admin

- url: /admin/.*
  script: admin.app
  secure: always
  login: admin

- url: /internal/.*
  script: admin.app
  secure: always
  login: admin

- url: /.*
  script: main.app
  secure: always

libraries:
- name: webapp2
  version: "2.5.2"
- name: jinja2
  version: latest
- name: PIL
  version: latest

#builtins:
#- datastore_admin: on
